config/routes.rb
SBFishing::Application.routes.draw do
  resources :posts
  match "/home" => "sb_fishing#home", via: :get

  match "/forum" => "sb_fishing#forum", via: :get

  match "/info" => "sb_fishing#info", via: :get

  match "/research" => "sb_fishing#research", via: :get

  match "/surf" => "sb_fishing#surf", via: :get

  match "/pier" => "sb_fishing#pier", via: :get

  match "/places" => "sb_fishing#places", via: :get

  root 'sb_fishing#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:topic, :date, :description)
    end
end

app/controllers/sb_fishing_controller.rb
class SbFishingController < ApplicationController
  def home
  	@title = 'Home'
  end



  def info
  	@title = 'Info'
  end

  def research
  	@title = 'Research'
  end

  def surf
  	@title = 'Surf'
  end

  def pier
  	@title = 'Pier'
  end

  def places
    @title = 'Places'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def title
		base_title = 'SB Fishing'
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sb_fishing_helper.rb
module SbFishingHelper
end

app/views/layouts/_footer.html.erb
<footer>
	©<%= Time.now.year%>
	Fishing Santa Barbara
</footer>

app/views/layouts/_header.html.erb
<header id='page_header'>

	<br>
	<br>
	<font size="10"><strong>Santa Barbara Fishing</strong></font>
	<br>
	<font size="5"><strong>The site for the Santa Barbara angler</strong></font>


</header>

app/views/layouts/_navigation.html.erb
<nav id="links" >
	<ul>
		<li> <%= link_to "Home", root_path %>
		<li> <%= link_to "Forum", posts_path %>
		<li> <%= link_to "About", info_path %>
		<li> <%= link_to "Research", research_path %>
		<ul class="sub_menu">
		</ul>

		<li> <%= link_to "Surf", surf_path %>
		<li> <%= link_to "Pier", pier_path %>
		<li> <%= link_to "Places", places_path %>
	</ul>
</nav>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
			<h1>Fish of the Day</h1>
			<h2>Halibut</h2>
			<p>
				While it is debatable whether the Wright brothers were in fact first to achieve powered flight, there is no doubt that the Wright Flyer was a revolutionary machine of its time. Developed with elements from the brothers’ glider designs with some aerodynamic aspects tested using a rudimentary wind tunnel, the Wright Flyer was a canard biplane with a wooden airframe and fabric-covered wings. It was powered by a four-cylinder, 12-horsepower engine, driving two large, wooden, pusher-propellers rotating in opposite directions. A stick-like wood lever controlled the pitch and the airplane was steered by wing warping achieved by the pilot by sliding left and right, cradled on a mobile platform. The Wright Flyers’ first flights on December 17, 1903, documented by still photography, made it one of the most famous airplanes in history. And the Wright brothers’ exhibitions in the United States and Europe inspired aspiring airplane manufacturers to engineer their own designs.
			</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
	<head>
	  <title><%=title%></title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	</head>

	<body id="page">


		<div id="container">

			<%= render 'layouts/header'%>
			<%= render 'layouts/navigation'%>

			<div id="sidebar">
				<h1>Fish of the Day</h1>
				<h2>California Halibut</h2>
				<img src="http://alex-cool.com/wp-content/uploads/california_halibut_fishid2.jpeg" alt="California Halibut" id="fish_image">
				<p>
					The California halibut or California flounder, <em>Paralichthys californicus</em>, is a large-tooth flounder native to the waters of the Pacific Coast of North America from the Quillayute River in Washington to Magdalena Bay in Baja California. It feeds near shore and is free swimming. It typically weighs 6 to 50 pounds (3 to 23 kg). It is much smaller than the larger and more northern-ranging Pacific halibut that can reach 300 pounds (140 kg).
				</p>
			</div>

			<div id="main">
				

				<%= yield %>

				<%= render 'layouts/footer'%>
			</div>

		</div>

		

	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>


  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :date %> :
    <%= Date.today %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forum</h1>



<article id="posts">
  <% @posts.each do |post| %>
    <section id="post">
      <div id="date"><h1>Posted: <%= post.created_at %></h1></div>
      <h2><%= post.topic %></h2>
      <p><%= post.description%></p>
        <p>
          <%= link_to 'Show', post %> |
          <%= link_to 'Edit', edit_post_path(post)%>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>

    </section>
  <%end%>

    <section>
      <%= link_to 'New Post', new_post_path %>
    </section>

</article>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @post.topic %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Posted:</strong>
  <%= @post.created_at %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/sb_fishing/home.html.erb
<h1>Home Page</h1>
<p>Welcome to SB Fishing</p>

<article>
	<div>

		


		<div id="main">
			<h1>Tides</h1>
			<p>
				While tides aren't the end all factor for the right time to go fishing, it is generally a good start for any unfamiliar beaches or casual fishermen. To look at the tide chart for your area, click the button below.
			</p>
			
			<button id="show_tides">Look for tides</button>
			<button id="hide_tides">Hide tide window</button>

			<section id="tide_frame">
				<p>Enter the city or town that you will be fishing in to view the current tide chart for that location.</p>
				<iframe src="http://tides.mobilegeographics.com/" id="tides">
			</section>
		</div>

		

	</div>
</article>

app/views/sb_fishing/info.html.erb
<h1>About</h1>
<article id="info">
	<section id="about_me">
		<h1>About Me</h1>
		<p>
			I grew up fishing the beaches and piers in the Santa Barbara area. I feel that the central coast has some of the best scenery and fishing in California.
		</p>
		<h1>My Philosophy</h1>
		<p>
			I've always felt that there is something valuable about being connected to the world around us, especially when it comes to the ecosystem. Humans may have climbed to be the apex organism on Earth, but we are still very connected to the other animals on this planet and we have more influence than ever. It is important to be conservative with our resources, which includes our many fisheries. The short term enjoyment of keeping all the fish we catch is not worth depleting these natural jewls in the long term.
		</p>
	</section>
	
	<section id="about_site">
		<h1>About this site</h1>
		<p>
			This site is dedicated to giving the angler all the information they want to increase their fishing knowlege and prowess in the waters in and around Santa Barbara waters.
		</p>
	</section>
</article>

app/views/sb_fishing/pier.html.erb
<div id="pier_image">
	<br>
	<font size="12"><strong><em>Pier Fishing</em></strong></font>

</div>
<p>Find me in app/views/sb_fishing/pier.html.erb</p>

app/views/sb_fishing/places.html.erb
<div id="places_image">
	<br>
	<font size="12"><strong><em>Places</em></strong></font>

</div>

app/views/sb_fishing/research.html.erb
<div id="research_image">
	<br>
	<font size="12"><strong><em>Research</em></strong></font>

</div>

app/views/sb_fishing/surf.html.erb
<div id="surf_image">
	<br>
	<font size="12"><strong><em>Surf Fishing</em></strong></font>

</div>
<p>Find me in app/views/sb_fishing/surf.html.erb</p>